(() => {
  const API='/api/cliente';
  const LABELS={received:'Pedido enviado',accepted:'Pedido aceptado',preparing:'En preparación',waiting_driver:'Esperando repartidor',out_for_delivery:'Salió para entrega',delivered:'Entregado',cancelled:'Cancelado'};
  const NEXT={received:'accepted',accepted:'preparing',preparing:'waiting_driver',waiting_driver:'out_for_delivery',out_for_delivery:'delivered'};
  const BTN={accepted:'ACEPTAR',preparing:'PREPARAR',waiting_driver:'ESPERANDO REPARTIDOR',out_for_delivery:'SALIR A ENTREGA',delivered:'MARCAR ENTREGADO'};
  let timer=null;
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  async function api(url=API,opt={}){const r=await fetch(url,{cache:'no-store',...opt}),d=await r.json().catch(()=>({}));if(r.status===401){window.parent.postMessage({type:'admin-session-expired'},'*');throw new Error('Sesión expirada.')}if(!r.ok)throw new Error(d.error||d.details||'Error');return d;}
  function style(){if(document.getElementById('ordersAdminStyles'))return;const s=document.createElement('style');s.id='ordersAdminStyles';s.textContent=`#ordersAdmin{max-width:1200px;margin:0 auto 20px;padding:0 20px}.orders-card{background:#fff;border-radius:12px;box-shadow:0 4px 15px rgba(0,0,0,.08);padding:20px}.orders-head{display:flex;justify-content:space-between;gap:12px;align-items:center}.orders-head h3{margin:0}.orders-refresh{width:auto!important;padding:8px 12px!important;font-size:12px!important;background:#eee;color:#6a0dad}.orders-grid{display:grid;gap:10px;margin-top:14px}.order-admin{border:1px solid #e8e1ec;border-radius:12px;padding:13px;background:#fff}.order-admin.active{border-left:5px solid #6a0dad}.order-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.order-code{font-weight:900;color:#6a0dad}.order-status{font-size:11px;font-weight:900;background:#f1e5fb;color:#6a0dad;padding:5px 8px;border-radius:999px}.order-meta{font-size:12px;color:#666;line-height:1.45;margin-top:7px}.order-items{font-size:12px;margin-top:7px;color:#333}.order-actions{display:flex;gap:7px;margin-top:11px;flex-wrap:wrap}.order-actions button{width:auto!important;flex:1;min-width:120px;padding:10px!important;font-size:11px!important}.order-next{background:#6a0dad;color:white}.order-cancel{background:#ff4444;color:white}.orders-empty{padding:18px;text-align:center;color:#888;font-size:13px}@media(max-width:600px){#ordersAdmin{padding:0 10px}.order-top{display:block}.order-status{display:inline-block;margin-top:6px}}`;document.head.appendChild(s);}
  function ensure(){style();if(document.getElementById('ordersAdmin'))return;const host=document.createElement('section');host.id='ordersAdmin';host.innerHTML=`<div class="orders-card"><div class="orders-head"><h3>🛵 Pedidos activos</h3><button class="orders-refresh" type="button">ACTUALIZAR</button></div><div id="ordersAdminList" class="orders-grid"><div class="orders-empty">Cargando pedidos...</div></div></div>`;const header=document.querySelector('header');if(header)header.insertAdjacentElement('afterend',host);else document.body.prepend(host);host.querySelector('.orders-refresh').onclick=load;}
  function fmt(ts){if(!ts)return'';try{return new Intl.DateTimeFormat('es-MX',{dateStyle:'short',timeStyle:'short',timeZone:'America/Cancun'}).format(new Date(ts));}catch{return ts}}
  function render(orders){const list=document.getElementById('ordersAdminList');if(!list)return;const active=orders.filter(o=>!['delivered','cancelled'].includes(o.status));const recentDone=orders.filter(o=>['delivered','cancelled'].includes(o.status)).slice(0,5);const show=[...active,...recentDone];if(!show.length){list.innerHTML='<div class="orders-empty">No hay pedidos todavía.</div>';return;}list.innerHTML=show.map(o=>{const next=NEXT[o.status];return `<article class="order-admin ${active.includes(o)?'active':''}" data-id="${esc(o.id)}"><div class="order-top"><div><div class="order-code">${esc(o.code)}</div><b>${esc(o.name||'Cliente')}</b></div><span class="order-status">${esc(LABELS[o.status]||o.status)}</span></div><div class="order-meta">${fmt(o.createdAt)} · ${o.fulfillment==='pickup'?'Recoger':'Envío'} · $${Number(o.total||0).toFixed(0)}<br>${esc(o.phone||'')}${o.address?` · ${esc(o.address)}`:''}</div><div class="order-items">${(o.items||[]).map(i=>`${Number(i.qty)||1}x ${esc(i.name)}`).join(' · ')}</div>${next||active.includes(o)?`<div class="order-actions">${next?`<button class="order-next" data-status="${next}">${BTN[next]||'AVANZAR'}</button>`:''}${active.includes(o)?'<button class="order-cancel" data-status="cancelled">CANCELAR</button>':''}</div>`:''}</article>`}).join('');list.querySelectorAll('button[data-status]').forEach(btn=>btn.onclick=()=>change(btn.closest('.order-admin').dataset.id,btn.dataset.status,btn));}
  async function change(id,status,btn){if(status==='cancelled'&&!confirm('¿Cancelar este pedido?'))return;const old=btn.textContent;btn.disabled=true;btn.textContent='ACTUALIZANDO...';try{await api(API,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'order_status',id,status})});await load();}catch(e){alert(e.message);}finally{if(btn.isConnected){btn.disabled=false;btn.textContent=old;}}}
  async function load(){ensure();const list=document.getElementById('ordersAdminList');try{const d=await api(`${API}?action=orders&admin=1&t=${Date.now()}`);render(Array.isArray(d.orders)?d.orders:[]);}catch(e){if(list)list.innerHTML=`<div class="orders-empty" style="color:#c0392b">${esc(e.message)}</div>`;}}
  function start(){ensure();load();clearInterval(timer);timer=setInterval(()=>{if(document.visibilityState==='visible')load();},12000);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
